name: DiscordConnect
version: '1.0-SNAPSHOT'
main: discordconnect.discordconnect.DiscordConnect
api-version: '1.20'

commands:
  gm:
    description: Toggles gamemode for the command sender
    usage: /gm
    aliases: gm
    permission: gamemode
    permission-message: You do not have permission
  burn:
    description: Burns the player
    usage: /burn
    aliases: burn
    permission: burn
    permission-message: You do not have permissio
  toss:
    description: Toss the player 100 blocks upper
    usage: /toss
    aliases: toss
    permission: toss
    permission-message: You do not have permission
  distance:
    description: Checks the distance between two players in blocks
    usage: /distance
    aliases: dist
    permission: distance
    permission-message: You do not have permission
  heal:
    description: Heals the player
    usage: /heal
    aliases: heal
    permission: heal
    permission-message: You do not have permission